spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:

server:
  port : 17641

jwt:
  secretkey: V3ryS3cr3t
  expiration_in_hours: 1