
spring:
#  h2.console:
#    enabled: true
#    path: /h2
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
#  datasource:
#    url: jdbc:mysql://localhost:3306/seed
#    username: seed
#    password: seedbe622yegQQ.u
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db
    username: admin
    password:
  mvc.pathmatch.matching-strategy: "ant_path_matcher"

server:
  port: 17641

jwt:
  secretkey: V3ryS3cr3t
  expiration_in_hours: 1

logging:
  level:
    org.springframework: ERROR
    com.nearsg.jobportal: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: app.log